version: "3.9"

services:
  db:
    image: mariadb:10            # ou mysql:8 si tu préfères
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"   # ← autorise root sans mot de passe
      MYSQL_DATABASE: TRANSPORT 
    volumes:
      - db_data:/var/lib/mysql         # persistance
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"                    # accès éventuel depuis ton IDE

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"                      # http://localhost:8080
    depends_on: [db]

  web:
    build: ./web
    volumes:
      - ./web:/var/www/html            # édition live de tes .php
    ports:
      - "8000:80"                      # http://localhost:8000
    depends_on: [db]

volumes:
  db_data: